# Generated by Django 3.1.5 on 2021-01-27 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtechtaxonomyitem',
            name='concept_id',
        ),
        migrations.RemoveField(
            model_name='jobtechtaxonomyitem',
            name='legacy_ams_taxonomy_id',
        ),
    ]
